"""create song table

Revision ID: 8dfa8ce6e866
Revises: 
Create Date: 2026-07-04 12:01:37.922565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa8ce6e866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('composer', sa.Text(), nullable=False),
    sa.Column('lyricist', sa.Text(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('archive', sa.Text(), nullable=False),
    sa.Column('bibliography', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('search_blob', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_composer'), ['composer'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_lyricist'), ['lyricist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    # ### end Alembic commands ###

    # --- Hand-written: FTS5 full-text index + sync triggers ---
    # Accent-insensitive search over the pre-folded search_blob column.
    # External-content table (content='song') addresses rows by song.id.
    op.execute("""
        CREATE VIRTUAL TABLE song_fts USING fts5(
            search_blob,
            content='song',
            content_rowid='id',
            tokenize='unicode61'
        )
    """)
    op.execute("""
        CREATE TRIGGER song_ai AFTER INSERT ON song BEGIN
            INSERT INTO song_fts(rowid, search_blob) VALUES (new.id, new.search_blob);
        END
    """)
    op.execute("""
        CREATE TRIGGER song_ad AFTER DELETE ON song BEGIN
            INSERT INTO song_fts(song_fts, rowid, search_blob)
            VALUES ('delete', old.id, old.search_blob);
        END
    """)
    op.execute("""
        CREATE TRIGGER song_au AFTER UPDATE ON song BEGIN
            INSERT INTO song_fts(song_fts, rowid, search_blob)
            VALUES ('delete', old.id, old.search_blob);
            INSERT INTO song_fts(rowid, search_blob) VALUES (new.id, new.search_blob);
        END
    """)


def downgrade():
    # Drop the hand-written FTS objects before the table they depend on.
    op.execute("DROP TRIGGER IF EXISTS song_au")
    op.execute("DROP TRIGGER IF EXISTS song_ad")
    op.execute("DROP TRIGGER IF EXISTS song_ai")
    op.execute("DROP TABLE IF EXISTS song_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_lyricist'))
        batch_op.drop_index(batch_op.f('ix_song_composer'))

    op.drop_table('song')
    # ### end Alembic commands ###
